/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApplicationsRouteImport } from './routes/applications'
import { Route as AuditRouteImport } from './routes/audit'
import { Route as CredentialsRouteImport } from './routes/credentials'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as SenderIdentitiesRouteImport } from './routes/sender-identities'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as TemplatesRouteImport } from './routes/templates'
import { Route as UsageRouteImport } from './routes/usage'
import { Route as UsersRouteImport } from './routes/users'
import { Route as WebhooksRouteImport } from './routes/webhooks'
import { Route as MessagesIndexRouteImport } from './routes/messages.index'
import { Route as MessagesMessageIdRouteImport } from './routes/messages.$messageId'
import { Route as MessagesBulkRouteImport } from './routes/messages.bulk'
import { Route as MessagesSendRouteImport } from './routes/messages.send'
import { Route as PlatformApiClientsRouteImport } from './routes/platform.api-clients'
import { Route as PlatformChannelsRouteImport } from './routes/platform.channels'
import { Route as PlatformConfigRouteImport } from './routes/platform.config'
import { Route as PlatformHealthRouteImport } from './routes/platform.health'
import { Route as PlatformPlansRouteImport } from './routes/platform.plans'
import { Route as PlatformProvidersRouteImport } from './routes/platform.providers'
import { Route as PlatformRoutingRouteImport } from './routes/platform.routing'
import { Route as PlatformTenantsRouteImport } from './routes/platform.tenants'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplicationsRoute = ApplicationsRouteImport.update({
  id: '/applications',
  path: '/applications',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditRoute = AuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const CredentialsRoute = CredentialsRouteImport.update({
  id: '/credentials',
  path: '/credentials',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const SenderIdentitiesRoute = SenderIdentitiesRouteImport.update({
  id: '/sender-identities',
  path: '/sender-identities',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const TemplatesRoute = TemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => rootRouteImport,
} as any)
const UsageRoute = UsageRouteImport.update({
  id: '/usage',
  path: '/usage',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersRoute = UsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => rootRouteImport,
} as any)
const WebhooksRoute = WebhooksRouteImport.update({
  id: '/webhooks',
  path: '/webhooks',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesIndexRoute = MessagesIndexRouteImport.update({
  id: '/messages/',
  path: '/messages/',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesMessageIdRoute = MessagesMessageIdRouteImport.update({
  id: '/messages/$messageId',
  path: '/messages/$messageId',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesBulkRoute = MessagesBulkRouteImport.update({
  id: '/messages/bulk',
  path: '/messages/bulk',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesSendRoute = MessagesSendRouteImport.update({
  id: '/messages/send',
  path: '/messages/send',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatformApiClientsRoute = PlatformApiClientsRouteImport.update({
  id: '/platform/api-clients',
  path: '/platform/api-clients',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatformChannelsRoute = PlatformChannelsRouteImport.update({
  id: '/platform/channels',
  path: '/platform/channels',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatformConfigRoute = PlatformConfigRouteImport.update({
  id: '/platform/config',
  path: '/platform/config',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatformHealthRoute = PlatformHealthRouteImport.update({
  id: '/platform/health',
  path: '/platform/health',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatformPlansRoute = PlatformPlansRouteImport.update({
  id: '/platform/plans',
  path: '/platform/plans',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatformProvidersRoute = PlatformProvidersRouteImport.update({
  id: '/platform/providers',
  path: '/platform/providers',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatformRoutingRoute = PlatformRoutingRouteImport.update({
  id: '/platform/routing',
  path: '/platform/routing',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatformTenantsRoute = PlatformTenantsRouteImport.update({
  id: '/platform/tenants',
  path: '/platform/tenants',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/applications': typeof ApplicationsRoute
  '/audit': typeof AuditRoute
  '/credentials': typeof CredentialsRoute
  '/docs': typeof DocsRoute
  '/login': typeof LoginRoute
  '/reports': typeof ReportsRoute
  '/sender-identities': typeof SenderIdentitiesRoute
  '/settings': typeof SettingsRoute
  '/templates': typeof TemplatesRoute
  '/usage': typeof UsageRoute
  '/users': typeof UsersRoute
  '/webhooks': typeof WebhooksRoute
  '/messages/$messageId': typeof MessagesMessageIdRoute
  '/messages/bulk': typeof MessagesBulkRoute
  '/messages/send': typeof MessagesSendRoute
  '/platform/api-clients': typeof PlatformApiClientsRoute
  '/platform/channels': typeof PlatformChannelsRoute
  '/platform/config': typeof PlatformConfigRoute
  '/platform/health': typeof PlatformHealthRoute
  '/platform/plans': typeof PlatformPlansRoute
  '/platform/providers': typeof PlatformProvidersRoute
  '/platform/routing': typeof PlatformRoutingRoute
  '/platform/tenants': typeof PlatformTenantsRoute
  '/messages/': typeof MessagesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/applications': typeof ApplicationsRoute
  '/audit': typeof AuditRoute
  '/credentials': typeof CredentialsRoute
  '/docs': typeof DocsRoute
  '/login': typeof LoginRoute
  '/reports': typeof ReportsRoute
  '/sender-identities': typeof SenderIdentitiesRoute
  '/settings': typeof SettingsRoute
  '/templates': typeof TemplatesRoute
  '/usage': typeof UsageRoute
  '/users': typeof UsersRoute
  '/webhooks': typeof WebhooksRoute
  '/messages/$messageId': typeof MessagesMessageIdRoute
  '/messages/bulk': typeof MessagesBulkRoute
  '/messages/send': typeof MessagesSendRoute
  '/platform/api-clients': typeof PlatformApiClientsRoute
  '/platform/channels': typeof PlatformChannelsRoute
  '/platform/config': typeof PlatformConfigRoute
  '/platform/health': typeof PlatformHealthRoute
  '/platform/plans': typeof PlatformPlansRoute
  '/platform/providers': typeof PlatformProvidersRoute
  '/platform/routing': typeof PlatformRoutingRoute
  '/platform/tenants': typeof PlatformTenantsRoute
  '/messages': typeof MessagesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/applications': typeof ApplicationsRoute
  '/audit': typeof AuditRoute
  '/credentials': typeof CredentialsRoute
  '/docs': typeof DocsRoute
  '/login': typeof LoginRoute
  '/reports': typeof ReportsRoute
  '/sender-identities': typeof SenderIdentitiesRoute
  '/settings': typeof SettingsRoute
  '/templates': typeof TemplatesRoute
  '/usage': typeof UsageRoute
  '/users': typeof UsersRoute
  '/webhooks': typeof WebhooksRoute
  '/messages/$messageId': typeof MessagesMessageIdRoute
  '/messages/bulk': typeof MessagesBulkRoute
  '/messages/send': typeof MessagesSendRoute
  '/platform/api-clients': typeof PlatformApiClientsRoute
  '/platform/channels': typeof PlatformChannelsRoute
  '/platform/config': typeof PlatformConfigRoute
  '/platform/health': typeof PlatformHealthRoute
  '/platform/plans': typeof PlatformPlansRoute
  '/platform/providers': typeof PlatformProvidersRoute
  '/platform/routing': typeof PlatformRoutingRoute
  '/platform/tenants': typeof PlatformTenantsRoute
  '/messages/': typeof MessagesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/applications'
    | '/audit'
    | '/credentials'
    | '/docs'
    | '/login'
    | '/reports'
    | '/sender-identities'
    | '/settings'
    | '/templates'
    | '/usage'
    | '/users'
    | '/webhooks'
    | '/messages/$messageId'
    | '/messages/bulk'
    | '/messages/send'
    | '/platform/api-clients'
    | '/platform/channels'
    | '/platform/config'
    | '/platform/health'
    | '/platform/plans'
    | '/platform/providers'
    | '/platform/routing'
    | '/platform/tenants'
    | '/messages/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/applications'
    | '/audit'
    | '/credentials'
    | '/docs'
    | '/login'
    | '/reports'
    | '/sender-identities'
    | '/settings'
    | '/templates'
    | '/usage'
    | '/users'
    | '/webhooks'
    | '/messages/$messageId'
    | '/messages/bulk'
    | '/messages/send'
    | '/platform/api-clients'
    | '/platform/channels'
    | '/platform/config'
    | '/platform/health'
    | '/platform/plans'
    | '/platform/providers'
    | '/platform/routing'
    | '/platform/tenants'
    | '/messages'
  id:
    | '__root__'
    | '/'
    | '/applications'
    | '/audit'
    | '/credentials'
    | '/docs'
    | '/login'
    | '/reports'
    | '/sender-identities'
    | '/settings'
    | '/templates'
    | '/usage'
    | '/users'
    | '/webhooks'
    | '/messages/$messageId'
    | '/messages/bulk'
    | '/messages/send'
    | '/platform/api-clients'
    | '/platform/channels'
    | '/platform/config'
    | '/platform/health'
    | '/platform/plans'
    | '/platform/providers'
    | '/platform/routing'
    | '/platform/tenants'
    | '/messages/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApplicationsRoute: typeof ApplicationsRoute
  AuditRoute: typeof AuditRoute
  CredentialsRoute: typeof CredentialsRoute
  DocsRoute: typeof DocsRoute
  LoginRoute: typeof LoginRoute
  ReportsRoute: typeof ReportsRoute
  SenderIdentitiesRoute: typeof SenderIdentitiesRoute
  SettingsRoute: typeof SettingsRoute
  TemplatesRoute: typeof TemplatesRoute
  UsageRoute: typeof UsageRoute
  UsersRoute: typeof UsersRoute
  WebhooksRoute: typeof WebhooksRoute
  MessagesMessageIdRoute: typeof MessagesMessageIdRoute
  MessagesBulkRoute: typeof MessagesBulkRoute
  MessagesSendRoute: typeof MessagesSendRoute
  PlatformApiClientsRoute: typeof PlatformApiClientsRoute
  PlatformChannelsRoute: typeof PlatformChannelsRoute
  PlatformConfigRoute: typeof PlatformConfigRoute
  PlatformHealthRoute: typeof PlatformHealthRoute
  PlatformPlansRoute: typeof PlatformPlansRoute
  PlatformProvidersRoute: typeof PlatformProvidersRoute
  PlatformRoutingRoute: typeof PlatformRoutingRoute
  PlatformTenantsRoute: typeof PlatformTenantsRoute
  MessagesIndexRoute: typeof MessagesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/applications': {
      id: '/applications'
      path: '/applications'
      fullPath: '/applications'
      preLoaderRoute: typeof ApplicationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit': {
      id: '/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/credentials': {
      id: '/credentials'
      path: '/credentials'
      fullPath: '/credentials'
      preLoaderRoute: typeof CredentialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sender-identities': {
      id: '/sender-identities'
      path: '/sender-identities'
      fullPath: '/sender-identities'
      preLoaderRoute: typeof SenderIdentitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/templates': {
      id: '/templates'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof TemplatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/usage': {
      id: '/usage'
      path: '/usage'
      fullPath: '/usage'
      preLoaderRoute: typeof UsageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users': {
      id: '/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/webhooks': {
      id: '/webhooks'
      path: '/webhooks'
      fullPath: '/webhooks'
      preLoaderRoute: typeof WebhooksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages/': {
      id: '/messages/'
      path: '/messages'
      fullPath: '/messages/'
      preLoaderRoute: typeof MessagesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages/$messageId': {
      id: '/messages/$messageId'
      path: '/messages/$messageId'
      fullPath: '/messages/$messageId'
      preLoaderRoute: typeof MessagesMessageIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages/bulk': {
      id: '/messages/bulk'
      path: '/messages/bulk'
      fullPath: '/messages/bulk'
      preLoaderRoute: typeof MessagesBulkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages/send': {
      id: '/messages/send'
      path: '/messages/send'
      fullPath: '/messages/send'
      preLoaderRoute: typeof MessagesSendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/platform/api-clients': {
      id: '/platform/api-clients'
      path: '/platform/api-clients'
      fullPath: '/platform/api-clients'
      preLoaderRoute: typeof PlatformApiClientsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/platform/channels': {
      id: '/platform/channels'
      path: '/platform/channels'
      fullPath: '/platform/channels'
      preLoaderRoute: typeof PlatformChannelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/platform/config': {
      id: '/platform/config'
      path: '/platform/config'
      fullPath: '/platform/config'
      preLoaderRoute: typeof PlatformConfigRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/platform/health': {
      id: '/platform/health'
      path: '/platform/health'
      fullPath: '/platform/health'
      preLoaderRoute: typeof PlatformHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/platform/plans': {
      id: '/platform/plans'
      path: '/platform/plans'
      fullPath: '/platform/plans'
      preLoaderRoute: typeof PlatformPlansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/platform/providers': {
      id: '/platform/providers'
      path: '/platform/providers'
      fullPath: '/platform/providers'
      preLoaderRoute: typeof PlatformProvidersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/platform/routing': {
      id: '/platform/routing'
      path: '/platform/routing'
      fullPath: '/platform/routing'
      preLoaderRoute: typeof PlatformRoutingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/platform/tenants': {
      id: '/platform/tenants'
      path: '/platform/tenants'
      fullPath: '/platform/tenants'
      preLoaderRoute: typeof PlatformTenantsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApplicationsRoute: ApplicationsRoute,
  AuditRoute: AuditRoute,
  CredentialsRoute: CredentialsRoute,
  DocsRoute: DocsRoute,
  LoginRoute: LoginRoute,
  ReportsRoute: ReportsRoute,
  SenderIdentitiesRoute: SenderIdentitiesRoute,
  SettingsRoute: SettingsRoute,
  TemplatesRoute: TemplatesRoute,
  UsageRoute: UsageRoute,
  UsersRoute: UsersRoute,
  WebhooksRoute: WebhooksRoute,
  MessagesMessageIdRoute: MessagesMessageIdRoute,
  MessagesBulkRoute: MessagesBulkRoute,
  MessagesSendRoute: MessagesSendRoute,
  PlatformApiClientsRoute: PlatformApiClientsRoute,
  PlatformChannelsRoute: PlatformChannelsRoute,
  PlatformConfigRoute: PlatformConfigRoute,
  PlatformHealthRoute: PlatformHealthRoute,
  PlatformPlansRoute: PlatformPlansRoute,
  PlatformProvidersRoute: PlatformProvidersRoute,
  PlatformRoutingRoute: PlatformRoutingRoute,
  PlatformTenantsRoute: PlatformTenantsRoute,
  MessagesIndexRoute: MessagesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
